"""Build Nova's avatar as a 3D photo-relief hologram of the exact reference image.

    python build_nova_relief.py <glb_out> [renders_dir]

The geometry is extruded from the reference portrait using an AI depth map
(tools/avatar/nova_portrait_depth.png, generated by Depth-Anything-V2), so
from the front the avatar IS the reference image — pixel-exact colors — with
real 3D relief for parallax, floating motion, glowing eyes and lip sync.

Inputs (already in tools/avatar/):
  nova_portrait_crop.png   the exact reference portrait (380x520)
  nova_portrait_depth.png  matching depth map (white = near)

Contract (matches frontend avatarContract.js / GlbAvatarSlot.jsx):
  Nova_Root > Head_Root > Nova_Face (shape keys: jawOpen, eyeBlink_L/R,
  mouthSmile_L/R) + EyeGlow_L/R; HUD_Root halo; clips: IdleHover, Blink,
  Speaking, Listening, Thinking, Happy, Alert, EyeGlowPulse, HUDRotate.

Landmarks measured from this crop (fractions, v from bottom):
  eyes v=0.504, eye centers u=0.5±0.171, mouth v=0.25.
"""
import math
import os
import random
import sys

import bpy
import numpy as np
from mathutils import Vector

GLB_OUT = sys.argv[1]
RENDER_DIR = sys.argv[2] if len(sys.argv) > 2 else None

HERE = os.path.dirname(os.path.abspath(__file__))
IMG_PATH = os.path.join(HERE, "nova_portrait_crop.png")
DEPTH_PATH = os.path.join(HERE, "nova_portrait_depth.png")

random.seed(7)
FPS = 30

PURPLE = (0.545, 0.361, 0.965, 1.0)
BLUE = (0.322, 0.659, 1.000, 1.0)
GOLD = (0.961, 0.772, 0.259, 1.0)

# Portrait landmarks (u from left, v from bottom)
EYE_V, EYE_SPAN, MOUTH_V = 0.504, 0.342, 0.25
CHIN_V = 0.138
EYE_L_U, EYE_R_U = 0.5 - EYE_SPAN / 2, 0.5 + EYE_SPAN / 2

# Composition (Blender Z-up, front = -Y, matches the previous pipeline)
PLANE_H = 1.9                # portrait height in scene units
PLANE_W = PLANE_H * (380 / 520)
BASE_Z = 0.55                # bottom of the portrait
RELIEF = 0.34                # how far the nose pushes toward the camera
GRID_NX, GRID_NY = 152, 208  # vertex grid


# ── helpers (same patterns as build_nova_avatar.py) ─────────────────────────

def clear_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()
    for block in (bpy.data.meshes, bpy.data.materials, bpy.data.images, bpy.data.actions, bpy.data.curves):
        for item in list(block):
            if item.users == 0:
                block.remove(item)


def make_material(name, base=PURPLE, emission=None, strength=1.0, alpha=1.0, rough=0.4, metal=0.05):
    mat = bpy.data.materials.new(name)
    try:
        mat.use_nodes = True
    except Exception:
        pass
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = base
    bsdf.inputs["Roughness"].default_value = rough
    bsdf.inputs["Metallic"].default_value = metal
    bsdf.inputs["Alpha"].default_value = alpha
    if emission is not None:
        bsdf.inputs["Emission Color"].default_value = emission
        bsdf.inputs["Emission Strength"].default_value = strength
    if alpha < 1.0:
        for attr, value in (("blend_method", "BLEND"), ("surface_render_method", "BLENDED")):
            try:
                setattr(mat, attr, value)
            except Exception:
                pass
    return mat


def new_empty(name, parent=None, location=(0, 0, 0)):
    empty = bpy.data.objects.new(name, None)
    empty.location = location
    bpy.context.collection.objects.link(empty)
    if parent is not None:
        empty.parent = parent
    return empty


def stash_clip(owner, action, clip_name, start=1):
    ad = owner.animation_data or owner.animation_data_create()
    ad.action = None
    track = ad.nla_tracks.new()
    track.name = clip_name
    strip = track.strips.new(action.name, int(start), action)
    strip.name = clip_name
    return strip


def animate_object(obj, clip_name, keys):
    ad = obj.animation_data or obj.animation_data_create()
    action = bpy.data.actions.new(f"{clip_name}_{obj.name}")
    ad.action = action
    try:
        if ad.action_slot is None and action.slots:
            ad.action_slot = action.slots[0]
    except Exception:
        pass
    for frame, values in keys:
        for path, value in values.items():
            setattr(obj, path, value)
            obj.keyframe_insert(data_path=path, frame=frame)
    stash_clip(obj, action, clip_name)


def animate_shape_keys(mesh_obj, clip_name, keys):
    shape_keys = mesh_obj.data.shape_keys
    ad = shape_keys.animation_data or shape_keys.animation_data_create()
    action = bpy.data.actions.new(f"{clip_name}_keys")
    ad.action = action
    try:
        if ad.action_slot is None and action.slots:
            ad.action_slot = action.slots[0]
    except Exception:
        pass
    names = set()
    for _, values in keys:
        names.update(values.keys())
    for frame, values in keys:
        for name in names:
            kb = shape_keys.key_blocks.get(name)
            if kb is None:
                continue
            kb.value = values.get(name, kb.value if frame > 1 else 0.0)
            kb.keyframe_insert(data_path="value", frame=frame)
    for name in names:
        kb = shape_keys.key_blocks.get(name)
        if kb is not None:
            kb.value = 0.0
    stash_clip(shape_keys, action, clip_name)


def load_pixels(path):
    img = bpy.data.images.load(path)
    w, h = img.size
    arr = np.array(img.pixels[:], dtype=np.float32).reshape(h, w, 4)  # bottom-up rows
    return img, arr, w, h


def sample(arr, u, v):
    """Bilinear-ish (nearest is fine at our density) sample, uv in [0,1]."""
    h, w = arr.shape[0], arr.shape[1]
    x = min(w - 1, max(0, int(round(u * (w - 1)))))
    y = min(h - 1, max(0, int(round(v * (h - 1)))))
    return arr[y, x]


# ── scene ────────────────────────────────────────────────────────────────────

clear_scene()
scene = bpy.context.scene
scene.render.fps = FPS

nova_root = new_empty("Nova_Root")
head_root = new_empty("Head_Root", parent=nova_root)

# 1) Portrait texture with silhouette alpha baked from the depth map
_, img_arr, IW, IH = load_pixels(IMG_PATH)
_, dep_arr, DW, DH = load_pixels(DEPTH_PATH)
depth = dep_arr[:, :, 0]  # grayscale

# Silhouette: background depth ~0 -> transparent, feathered
lo, hi = 0.06, 0.18
alpha = np.clip((depth - lo) / (hi - lo), 0.0, 1.0)
# Hologram-style fade at the bottom edge (shoulder crop line)
vv = np.linspace(0.0, 1.0, IH)[:, None]  # bottom-up
alpha *= np.clip(vv / 0.10, 0.0, 1.0) ** 0.8
# Slight overall translucency at the rim for a light-projection feel
rgba = img_arr.copy()
rgba[:, :, 3] = alpha

tex = bpy.data.images.new("NovaPortraitRGBA", width=IW, height=IH, alpha=True)
tex.pixels = rgba.reshape(-1).tolist()
tex.pack()

# Center of the WHOLE head: horizontally the silhouette centroid; vertically
# the midpoint of the head's full extent (hair top -> chin). An area centroid
# would drift up toward the wide hair mass and center the halo on the top of
# the head instead of the whole head.
head_rows = alpha[int(IH * 0.35):, :]  # bottom-up array: v > 0.35
ys, xs = np.nonzero(head_rows > 0.5)
if len(xs):
    HEAD_CU = float(xs.mean()) / (IW - 1)
else:
    HEAD_CU = 0.5

row_coverage = (alpha > 0.5).mean(axis=1)  # fraction of each row that is head
covered = np.nonzero(row_coverage > 0.02)[0]
HAIR_TOP_V = float(covered.max()) / (IH - 1) if len(covered) else 0.97
HEAD_CV = (HAIR_TOP_V + CHIN_V) / 2
HEAD_CZ = BASE_Z + HEAD_CV * PLANE_H

# Optical lift: the halo anchors slightly BELOW the geometric head center so
# her head rides a little high in the rings (dead-center reads as low).
HEAD_LIFT = 0.07
HALO_CZ = HEAD_CZ - HEAD_LIFT
print(f"head center: u={HEAD_CU:.3f} hair_top_v={HAIR_TOP_V:.3f} chin_v={CHIN_V} -> v_mid={HEAD_CV:.3f} z={HEAD_CZ:.3f} halo_z={HALO_CZ:.3f}")

# 2) Relief mesh: grid displaced by depth toward the camera (-Y)
# The mesh is SPLIT along her lip line so the mouth actually OPENS (lips are
# separate geometry that parts, with teeth + dark cavity behind) instead of
# the texture stretching. Seam vertices inside the mouth span are duplicated:
# originals belong to the upper lip, copies to the lower lip/jaw.
LIP_V = 0.255                 # her lip meeting line (v from bottom)
MOUTH_U0, MOUTH_U1 = 0.415, 0.585
J_LIP = round(LIP_V * (GRID_NY - 1))

verts, uv_of = [], []
for j in range(GRID_NY):
    v = j / (GRID_NY - 1)
    for i in range(GRID_NX):
        u = i / (GRID_NX - 1)
        d = float(sample(dep_arr, u, v)[0])
        verts.append(((u - HEAD_CU) * PLANE_W, -d * RELIEF, BASE_Z + v * PLANE_H))
        uv_of.append((u, v))

lower_dup = {}  # column index -> duplicated seam vertex (lower-lip copy)
for i in range(GRID_NX):
    u = i / (GRID_NX - 1)
    if MOUTH_U0 <= u <= MOUTH_U1:
        src = J_LIP * GRID_NX + i
        lower_dup[i] = len(verts)
        verts.append(verts[src])
        uv_of.append(uv_of[src])
dup_set = set(lower_dup.values())

faces = []
for j in range(GRID_NY - 1):
    for i in range(GRID_NX - 1):
        a = j * GRID_NX + i
        quad = [a, a + 1, a + GRID_NX + 1, a + GRID_NX]
        if j == J_LIP - 1:  # cells whose TOP edge lies on the lip seam
            if (i + 1) in lower_dup:
                quad[2] = lower_dup[i + 1]
            if i in lower_dup:
                quad[3] = lower_dup[i]
        faces.append(tuple(quad))

mesh = bpy.data.meshes.new("Nova_Face")
mesh.from_pydata(verts, [], faces)
mesh.update()
uv_layer = mesh.uv_layers.new(name="UVMap")
for poly in mesh.polygons:
    for li in poly.loop_indices:
        uv_layer.data[li].uv = uv_of[mesh.loops[li].vertex_index]

face_obj = bpy.data.objects.new("Nova_Face", mesh)
bpy.context.collection.objects.link(face_obj)
face_obj.parent = head_root
bpy.context.view_layer.objects.active = face_obj
face_obj.select_set(True)
bpy.ops.object.shade_smooth()

mat = make_material("NovaHolo_Portrait3D", base=(1, 1, 1, 1), emission=(1, 1, 1, 1), strength=0.62, alpha=1.0, rough=0.55)
nodes, links = mat.node_tree.nodes, mat.node_tree.links
bsdf = nodes.get("Principled BSDF")
tex_node = nodes.new("ShaderNodeTexImage")
tex_node.image = tex
tex_node.extension = "EXTEND"
links.new(tex_node.outputs["Color"], bsdf.inputs["Base Color"])
links.new(tex_node.outputs["Color"], bsdf.inputs["Emission Color"])
links.new(tex_node.outputs["Alpha"], bsdf.inputs["Alpha"])
for attr, value in (("blend_method", "BLEND"), ("surface_render_method", "BLENDED")):
    try:
        setattr(mat, attr, value)
    except Exception:
        pass
try:
    mat.use_backface_culling = True
except Exception:
    pass
mesh.materials.append(mat)

# 3) Shape keys at the measured landmarks
basis = face_obj.shape_key_add(name="Basis", from_mix=False)


def region_key(name, center_u, center_v, ru, rv, move, domain=None):
    """Add a shape key displacing verts inside an ellipse with smooth falloff.

    move(weight, u, v) -> (dx, dy, dz); domain(vi, u, v) -> bool limits which
    vertices may move (used to keep the upper lip still while the jaw opens).
    """
    kb = face_obj.shape_key_add(name=name, from_mix=False)
    for vi, vert in enumerate(mesh.vertices):
        u, v = uv_of[vi]
        if domain is not None and not domain(vi, u, v):
            continue
        du, dv = (u - center_u) / ru, (v - center_v) / rv
        dist2 = du * du + dv * dv
        if dist2 >= 1.0:
            continue
        weight = (1.0 - dist2) ** 1.5
        dx, dy, dz = move(weight, u, v)
        co = vert.co
        kb.data[vi].co = (co.x + dx, co.y + dy, co.z + dz)
    return kb


def _lower_jaw_domain(vi, u, v):
    """Lower lip + chin only: seam duplicates and everything below the seam."""
    return vi in dup_set or v < LIP_V - 1e-6


jaw_drop = PLANE_H * 0.045
region_key(
    "jawOpen", 0.5, MOUTH_V - 0.035, 0.20, 0.16,
    lambda w, u, v: (0.0, 0.012 * w, -jaw_drop * w),
    domain=_lower_jaw_domain,
)

# Mouth interior: revealed when the lips part. A dark oral cavity plane and
# an upper-teeth strip sit just behind the lip seam.
d_mouth = float(sample(dep_arr, 0.5, MOUTH_V)[0])
mouth_x = (0.5 - HEAD_CU) * PLANE_W
lip_z = BASE_Z + LIP_V * PLANE_H
lip_y = -d_mouth * RELIEF

mat_cavity = make_material("NovaHolo_MouthCavity", base=(0.05, 0.015, 0.045, 1.0), emission=(0.04, 0.01, 0.035, 1.0), strength=0.12, alpha=1.0, rough=0.85)
bpy.ops.mesh.primitive_plane_add(size=1, location=(mouth_x, lip_y + 0.075, lip_z - 0.035 * PLANE_H))
cavity = bpy.context.active_object
cavity.name = "Mouth_Cavity"
cavity.rotation_euler = (math.pi / 2, 0, 0)  # face the camera (-Y)
cavity.scale = (PLANE_W * 0.215, PLANE_H * 0.105, 1)
cavity.data.materials.append(mat_cavity)
cavity.parent = head_root

mat_teeth = make_material("NovaHolo_Teeth", base=(0.76, 0.73, 0.86, 1.0), emission=(0.32, 0.30, 0.44, 1.0), strength=0.10, alpha=1.0, rough=0.55)
bpy.ops.mesh.primitive_cube_add(size=1, location=(mouth_x, lip_y + 0.045, lip_z - 0.002 * PLANE_H))
teeth = bpy.context.active_object
teeth.name = "Mouth_Teeth"
teeth.scale = (PLANE_W * 0.115, 0.018, PLANE_H * 0.015)
teeth.data.materials.append(mat_teeth)
teeth.parent = head_root

# Blink: vertical squeeze toward the eye line (upper lid down, lower lid up)
blink_squeeze = PLANE_H * 0.016
for suffix, eu in (("L", EYE_L_U), ("R", EYE_R_U)):
    region_key(
        f"eyeBlink_{suffix}", eu, EYE_V, 0.085, 0.052,
        lambda w, u, v: (0.0, 0.006 * w, -blink_squeeze * w * (1 if v > EYE_V else -1)),
    )

smile_lift = PLANE_H * 0.012
for suffix, cu in (("L", 0.5 - 0.11), ("R", 0.5 + 0.11)):
    region_key(
        f"mouthSmile_{suffix}", cu, MOUTH_V + 0.01, 0.08, 0.06,
        lambda w, u, v: (0.0, 0.0, smile_lift * w),
    )

# 4) Eye glow accents (her eyes already glow in the image — this adds live pulse)
# Her irises already glow in the photo itself — these are only a faint aura,
# mostly tucked BEHIND the relief surface so they halo the eyes without
# covering them (previous builds washed the eyes out with front-facing glow).
mat_glow = make_material("NovaHolo_EyeGlow", base=PURPLE, emission=PURPLE, strength=0.45, alpha=0.12)
glow_objs = []
for suffix, eu in (("L", EYE_L_U), ("R", EYE_R_U)):
    x = (eu - HEAD_CU) * PLANE_W
    z = BASE_Z + EYE_V * PLANE_H
    d = float(sample(dep_arr, eu, EYE_V)[0])
    bpy.ops.mesh.primitive_uv_sphere_add(segments=16, ring_count=12, radius=0.055, location=(x, -d * RELIEF + 0.02, z))
    glow = bpy.context.active_object
    glow.name = f"EyeGlow_{suffix}"
    glow.scale = (1, 0.3, 0.72)
    glow.data.materials.append(mat_glow)
    glow.parent = head_root
    glow_objs.append(glow)

# 5) HUD halo behind her (matches the reference image's ring composition)
# Halo anchored just below head center (optical lift — see HEAD_LIFT)
hud_root = new_empty("HUD_Root", parent=nova_root, location=(0, 0.35, HALO_CZ))
mat_ring_p = make_material("NovaHolo_HUDPurple", base=PURPLE, emission=PURPLE, strength=1.4, alpha=0.8)
mat_ring_b = make_material("NovaHolo_HUDBlue", base=BLUE, emission=BLUE, strength=1.2, alpha=0.7)
mat_ring_g = make_material("NovaHolo_HUDGold", base=GOLD, emission=GOLD, strength=1.5, alpha=0.85)

spin_a = new_empty("HUD_Spin_A", parent=hud_root)
spin_b = new_empty("HUD_Spin_B", parent=hud_root)
spin_c = new_empty("HUD_Spin_C", parent=hud_root)

for name, major, minor, mat_ring, parent in (
    ("HUD_Ring_Outer", 1.18, 0.007, mat_ring_p, spin_a),
    ("HUD_Ring_Mid", 1.02, 0.005, mat_ring_b, spin_b),
    ("HUD_Ring_Inner", 0.86, 0.006, mat_ring_p, spin_c),
):
    bpy.ops.mesh.primitive_torus_add(major_radius=major, minor_radius=minor, rotation=(math.pi / 2, 0, 0),
                                     major_segments=96, minor_segments=8)
    ring = bpy.context.active_object
    ring.name = name
    ring.data.materials.append(mat_ring)
    ring.parent = parent
    bpy.ops.object.shade_smooth()

tick_objs = []
for i in range(72):
    a = i / 72 * 2 * math.pi
    bpy.ops.mesh.primitive_cube_add(size=1, location=(math.cos(a) * 1.26, 0, math.sin(a) * 1.26))
    tick = bpy.context.active_object
    tick.scale = (0.004, 0.004, 0.03 if i % 6 else 0.05)
    tick.rotation_euler = (0, -a, 0)
    tick_objs.append(tick)
bpy.ops.object.select_all(action="DESELECT")
for t in tick_objs:
    t.select_set(True)
bpy.context.view_layer.objects.active = tick_objs[0]
bpy.ops.object.join()
ticks = bpy.context.active_object
ticks.name = "HUD_Ticks"
ticks.data.materials.append(mat_ring_b)
ticks.parent = spin_a

for arc_name, radius, a0, a1, mat_ring, parent in (
    ("HUD_Arc_Gold", 1.10, 25, 125, mat_ring_g, spin_b),
    ("HUD_Arc_Blue", 0.94, 205, 280, mat_ring_b, spin_c),
):
    curve = bpy.data.curves.new(arc_name, type="CURVE")
    curve.dimensions = "3D"
    curve.bevel_depth = 0.008
    curve.bevel_resolution = 2
    spline = curve.splines.new("POLY")
    steps = 28
    spline.points.add(steps)
    for k in range(steps + 1):
        a = math.radians(a0 + (a1 - a0) * k / steps)
        spline.points[k].co = (math.cos(a) * radius, 0, math.sin(a) * radius, 1)
    obj = bpy.data.objects.new(arc_name, curve)
    bpy.context.collection.objects.link(obj)
    obj.parent = parent
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.ops.object.convert(target="MESH")
    obj.data.materials.append(mat_ring)

particle_objs = []
for i in range(60):
    a = random.uniform(0, 2 * math.pi)
    r = random.uniform(0.7, 1.36)
    bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=1, radius=random.uniform(0.004, 0.010),
                                          location=(math.cos(a) * r, random.uniform(-0.1, 0.1), math.sin(a) * r))
    particle_objs.append(bpy.context.active_object)
bpy.ops.object.select_all(action="DESELECT")
for p in particle_objs:
    p.select_set(True)
bpy.context.view_layer.objects.active = particle_objs[0]
bpy.ops.object.join()
particles = bpy.context.active_object
particles.name = "HUD_Particles"
particles.data.materials.append(make_material("NovaHolo_Particle", base=PURPLE, emission=PURPLE, strength=2.0, alpha=0.75))
particles.parent = spin_b

# 6) Camera + soft lights (for verification renders; hidden by the app)
cam_data = bpy.data.cameras.new("Nova_Camera")
cam = bpy.data.objects.new("Nova_Camera", cam_data)
cam.location = (0, -4.0, HALO_CZ)
cam.rotation_euler = (math.pi / 2, 0, 0)
bpy.context.collection.objects.link(cam)
scene.camera = cam

for lname, loc, energy in (("Light_Key", (0.9, -2.6, 2.4), 60), ("Light_Rim", (-1.1, 1.6, 2.1), 40)):
    ldata = bpy.data.lights.new(lname, type="AREA")
    ldata.energy = energy
    ldata.color = (0.8, 0.75, 1.0)
    ldata.size = 2.0
    lobj = bpy.data.objects.new(lname, ldata)
    lobj.location = loc
    lobj.rotation_euler = (Vector((0, 0, 1.4)) - Vector(loc)).to_track_quat("-Z", "Y").to_euler()
    bpy.context.collection.objects.link(lobj)


# ── animation clips ──────────────────────────────────────────────────────────

def deg(x):
    return math.radians(x)


animate_object(nova_root, "IdleHover", [
    (1, {"location": (0, 0, 0.0), "rotation_euler": (0, 0, 0)}),
    (80, {"location": (0, 0, 0.028), "rotation_euler": (deg(0.4), 0, deg(1.4))}),
    (160, {"location": (0, 0, -0.014), "rotation_euler": (deg(-0.4), 0, deg(-1.4))}),
    (240, {"location": (0, 0, 0.0), "rotation_euler": (0, 0, 0)}),
])

animate_object(spin_a, "HUDRotate", [(1, {"rotation_euler": (0, 0, 0)}), (900, {"rotation_euler": (0, deg(360), 0)})])
animate_object(spin_b, "HUDRotate", [(1, {"rotation_euler": (0, 0, 0)}), (900, {"rotation_euler": (0, deg(-360), 0)})])
animate_object(spin_c, "HUDRotate", [(1, {"rotation_euler": (0, 0, 0)}), (900, {"rotation_euler": (0, deg(540), 0)})])

for glow in glow_objs:
    base_scale = tuple(glow.scale)
    animate_object(glow, "EyeGlowPulse", [
        (1, {"scale": base_scale}),
        (45, {"scale": tuple(s * 1.22 for s in base_scale)}),
        (90, {"scale": base_scale}),
    ])

animate_shape_keys(face_obj, "Blink", [
    (1, {"eyeBlink_L": 0.0, "eyeBlink_R": 0.0}),
    (5, {"eyeBlink_L": 1.0, "eyeBlink_R": 1.0}),
    (11, {"eyeBlink_L": 0.0, "eyeBlink_R": 0.0}),
])

speak_keys = [(1, {"jawOpen": 0.0})]
for frame in range(7, 73, 6):
    speak_keys.append((frame, {"jawOpen": random.uniform(0.15, 0.6)}))
speak_keys.append((72, {"jawOpen": 0.0}))
animate_shape_keys(face_obj, "Speaking", speak_keys)

animate_shape_keys(face_obj, "Happy", [
    (1, {"mouthSmile_L": 0.0, "mouthSmile_R": 0.0}),
    (16, {"mouthSmile_L": 0.8, "mouthSmile_R": 0.75}),
    (45, {"mouthSmile_L": 0.8, "mouthSmile_R": 0.75}),
])

animate_object(head_root, "Listening", [
    (1, {"rotation_euler": (0, 0, 0)}),
    (14, {"rotation_euler": (deg(1.2), 0, deg(2.6))}),
    (90, {"rotation_euler": (deg(1.2), 0, deg(2.6))}),
])
animate_object(head_root, "Thinking", [
    (1, {"rotation_euler": (0, 0, 0)}),
    (18, {"rotation_euler": (deg(-1.8), 0, deg(-2.2))}),
    (120, {"rotation_euler": (deg(-1.8), 0, deg(-2.2))}),
])
animate_object(head_root, "Alert", [
    (1, {"rotation_euler": (0, 0, 0), "location": (0, 0, 0)}),
    (8, {"rotation_euler": (deg(1.5), 0, 0), "location": (0, 0, 0.02)}),
    (30, {"rotation_euler": (deg(1.5), 0, 0), "location": (0, 0, 0.02)}),
])

# ── export ───────────────────────────────────────────────────────────────────
bpy.ops.object.select_all(action="SELECT")
export_kwargs = dict(
    filepath=GLB_OUT,
    export_format="GLB",
    export_animation_mode="NLA_TRACKS",
    export_cameras=True,
    export_morph=True,
    export_yup=True,
    export_apply=False,
)
try:
    bpy.ops.export_scene.gltf(**export_kwargs)
except TypeError:
    bpy.ops.export_scene.gltf(**{k: v for k, v in export_kwargs.items() if k != "export_cameras"})
print("EXPORTED:", GLB_OUT)

# ── verification renders ─────────────────────────────────────────────────────
if RENDER_DIR:
    os.makedirs(RENDER_DIR, exist_ok=True)
    for datablock in list(bpy.data.objects) + [face_obj.data.shape_keys]:
        ad = getattr(datablock, "animation_data", None)
        if ad:
            for tr in ad.nla_tracks:
                tr.mute = True

    scene.render.engine = "CYCLES"
    scene.cycles.samples = 24
    try:
        scene.cycles.use_denoising = False
    except Exception:
        pass
    scene.render.resolution_x = 512
    scene.render.resolution_y = 640
    world = bpy.data.worlds.new("NovaWorld")
    world.use_nodes = True
    bg = world.node_tree.nodes.get("Background")
    if bg:
        bg.inputs[0].default_value = (0.004, 0.003, 0.012, 1.0)
    scene.world = world

    def snap(name):
        scene.render.filepath = os.path.join(RENDER_DIR, name)
        bpy.ops.render.render(write_still=True)
        print("RENDERED:", name)

    kb = face_obj.data.shape_keys.key_blocks
    snap("front.png")

    kb["jawOpen"].value = 0.65
    snap("jaw_open.png")
    kb["jawOpen"].value = 0.0

    kb["eyeBlink_L"].value = 1.0
    kb["eyeBlink_R"].value = 1.0
    snap("blink.png")
    kb["eyeBlink_L"].value = 0.0
    kb["eyeBlink_R"].value = 0.0

    # Slight side angle to show the 3D relief
    cam.location = (1.1, -3.8, BASE_Z + PLANE_H * 0.55)
    cam.rotation_euler = (math.pi / 2, 0, math.radians(16))
    snap("angle.png")
