"""What state a piece of work is actually in, and why (Stage 14).

Before this existed, "complete" came from three lines that asked whether the
program started and whether tests Nova generated by reading her own output
objected. The user's request was not part of that decision, so there was
nothing to compare the result against. A calculator asked to add and subtract,
which could only add, was `complete`.

This module is the replacement, and it is deliberately a PURE function of
recorded facts. No I/O, no clock, no model, no project directory. Give it a
requirement, its criteria, and the evidence gathered against them, and it
returns one state and the reasons for it. That property is the point: a writer
cannot reach in and assign a state, because there is nothing here to assign
to — the state is derived every time it is asked for.

THREE RULES THAT SHAPE EVERYTHING HERE

1. CRITERIA COME FROM THE REQUEST, NOT FROM THE CODE.
   A criterion carries `origin_quote`: the span of the user's own durable
   request it was derived from. Criteria are recorded BEFORE implementation.
   Deriving an acceptance contract from finished code is circular — it asks
   the artifact to certify itself, and it can only ever conclude that the code
   does what the code does.

2. EVIDENCE IS FENCED TO WHAT IT ACTUALLY EXAMINED.
   Evidence carries the requirement revision it was gathered under and the
   digest of the implementation it examined. When either moves on, that
   evidence stops counting toward the current state. It stays in history; it
   just cannot speak for a thing it never saw.

3. WHAT WAS NEVER CHECKED IS NOT PASSED.
   "No automated tests were applicable" is not a pass. Silence is `PENDING`,
   and a required criterion that is `PENDING` is not `COMPLETE`.

See `docs/NOVA_V3_STAGE14_COMPLETION_MAP.md` for what this replaces.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Sequence

# ── The seven states ────────────────────────────────────────────────────────
#
# Not monotonic, on purpose. Adding a requirement to a COMPLETE project makes
# it PARTIALLY_IMPLEMENTED again; an artifact changing underneath COMPLETE
# evidence takes it back too. History stays history; current truth is current.

IDEA = "idea"
PLANNED = "planned"
SCAFFOLDED = "scaffolded"
PARTIALLY_IMPLEMENTED = "partially_implemented"
FAILING = "failing"
PASSING = "passing"
COMPLETE = "complete"

STATES = (IDEA, PLANNED, SCAFFOLDED, PARTIALLY_IMPLEMENTED,
          FAILING, PASSING, COMPLETE)

#: Human-facing one-liners. Used by chat so the wording cannot drift from the
#: state it describes.
STATE_MEANING = {
    IDEA: "asked for, but there is no accepted acceptance contract yet",
    PLANNED: "requirements and acceptance criteria exist; the implementation "
             "does not yet meaningfully satisfy them",
    SCAFFOLDED: "files exist, but no required criterion has been demonstrated yet",
    PARTIALLY_IMPLEMENTED: "some required criteria are demonstrated; others are "
                           "still unproven",
    FAILING: "a required criterion is currently failing",
    PASSING: "every machine-checkable required criterion passes, but final "
             "acceptance is still outstanding",
    COMPLETE: "every required criterion has current passing or accepted evidence",
}

# ── Verdicts a single criterion can carry ───────────────────────────────────

PENDING = "pending"          # nothing current says anything about it
PASSED = "passed"            # a current check demonstrated it
FAILED = "failed"            # a current check refuted it
HUMAN_PENDING = "human_pending"   # only a person can judge; they have not yet
WAIVED = "waived"            # a person explicitly accepted it without proof
INCONCLUSIVE = "inconclusive"     # a check ran and could not decide

VERDICTS = (PENDING, PASSED, FAILED, HUMAN_PENDING, WAIVED, INCONCLUSIVE)

#: Verdicts that let a required criterion count as satisfied. Deliberately
#: short. INCONCLUSIVE is not here: a check that could not decide has not
#: decided, and that was exactly the old "no tests were applicable" hole.
SATISFYING = frozenset({PASSED, WAIVED})

#: Verdicts that mean "nobody has demonstrated this yet" as opposed to
#: "somebody demonstrated it is wrong".
UNPROVEN = frozenset({PENDING, HUMAN_PENDING, INCONCLUSIVE})


@dataclass(frozen=True)
class Criterion:
    """One acceptance criterion, traced to the request that produced it."""

    criterion_id: str
    text: str
    #: The user's own words this was derived from. A criterion that cannot
    #: point at the request is not an acceptance criterion, it is an opinion.
    origin_quote: str
    #: user | plan | human — where the criterion came from. `plan` criteria are
    #: a model's decomposition of a user requirement and must still quote it.
    source: str = "user"
    required: bool = True
    #: machine | human. A human criterion can never be satisfied by a machine
    #: check; pretending otherwise is fabricating evidence.
    verify_kind: str = "machine"
    revision: int = 1
    #: The criterion at an earlier revision this one continues, if any. Used
    #: ONLY to explain why something already demonstrated needs demonstrating
    #: again — never to satisfy it, because the requirement it was proven under
    #: is not the requirement in force.
    carried_from: str = ""


@dataclass(frozen=True)
class Evidence:
    """One recorded observation about one criterion."""

    criterion_id: str
    verdict: str
    #: The requirement revision this was gathered under.
    revision: int
    #: Digest of the IMPLEMENTATION artifacts examined. See
    #: `implementation_digest` for what is deliberately excluded.
    artifact_digest: str
    detail: str = ""
    error: str = ""
    created_at: str = ""
    task_id: str | None = None
    generation: int | None = None
    attempt: int | None = None
    #: For a waiver, the human decision it answers. A waived row without one is
    #: an acceptance nobody was asked for, and is not honoured.
    decision_id: str | None = None


@dataclass(frozen=True)
class CriterionStatus:
    """A criterion plus the verdict that currently applies to it."""

    criterion: Criterion
    verdict: str
    evidence: Evidence | None
    #: Why current evidence does not apply, when it does not. Empty otherwise.
    stale_reason: str = ""


@dataclass(frozen=True)
class Verdict:
    """The answer, and enough of the working to argue with it."""

    state: str
    reasons: tuple[str, ...] = ()
    criteria: tuple[CriterionStatus, ...] = ()
    revision: int = 0
    artifact_digest: str = ""
    #: Required criteria not yet satisfied, in recorded order. This is what
    #: "what's left?" answers from.
    outstanding: tuple[CriterionStatus, ...] = ()
    failing: tuple[CriterionStatus, ...] = ()
    #: A pre-Stage-14 status string found in storage, if any. Never promoted
    #: into `state` — see `legacy_note`.
    legacy_status: str = ""
    legacy_note: str = ""

    @property
    def is_complete(self) -> bool:
        return self.state == COMPLETE

    def summary(self) -> str:
        """One line a person can read. Never claims more than `state` says."""
        head = f"{self.state}: {STATE_MEANING.get(self.state, '')}"
        if self.failing:
            head += f" — failing: {self.failing[0].criterion.text}"
        elif self.outstanding:
            head += f" — outstanding: {self.outstanding[0].criterion.text}"
        return head


def current_verdict_for(criterion: Criterion,
                        evidence: Sequence[Evidence],
                        *, revision: int,
                        artifact_digest: str) -> CriterionStatus:
    """The verdict that applies to this criterion RIGHT NOW.

    Evidence is admissible only if it was gathered for the current requirement
    revision AND against the current implementation. Anything else is history:
    it is reported as the reason the criterion is unproven, never as proof.

    The most recent admissible observation wins. A criterion that passed and
    was then refuted is failing; one that failed and was then repaired is
    passing. Ordering is by the order evidence was recorded, which the caller
    supplies — this function does not consult a clock.
    """
    admissible: list[Evidence] = []
    stale_reason = ""
    for ev in evidence:
        if ev.criterion_id != criterion.criterion_id:
            continue
        if int(ev.revision) != int(revision):
            stale_reason = (f"evidence was gathered for requirement revision "
                            f"{ev.revision}, and the requirement is now on "
                            f"{revision}")
            continue
        if ev.artifact_digest != artifact_digest:
            # EXACT equality, in both directions. The first version skipped this
            # comparison when either side was empty, which made evidence
            # recorded against no implementation at all a wildcard: it went on
            # certifying whatever was built afterwards, because "" was treated
            # as "no opinion" rather than as "there was nothing here".
            was = ev.artifact_digest[:12] or "no implementation"
            now = artifact_digest[:12] or "no implementation"
            stale_reason = ("the implementation changed after this was checked "
                            f"({was} -> {now})")
            continue
        admissible.append(ev)

    if not admissible:
        if not stale_reason and criterion.carried_from:
            # Nothing was recorded against THIS criterion, but its ancestor was
            # proven under an earlier requirement. Saying so is the difference
            # between "this was never checked" and "you saw this pass, and then
            # the requirement moved".
            prior = [e for e in evidence
                     if e.criterion_id == criterion.carried_from]
            if prior:
                stale_reason = (
                    f"demonstrated under requirement revision "
                    f"{prior[-1].revision}, which the requirement has since "
                    f"moved past; it needs checking again")
        # A human criterion with nothing said about it is waiting on a person,
        # not merely unstarted — which is a different sentence to the user.
        verdict = HUMAN_PENDING if criterion.verify_kind == "human" else PENDING
        return CriterionStatus(criterion=criterion, verdict=verdict,
                               evidence=None, stale_reason=stale_reason)

    latest = admissible[-1]
    verdict = latest.verdict if latest.verdict in VERDICTS else PENDING
    if verdict == WAIVED and not latest.decision_id:
        # An acceptance that answers no question. The service cannot produce
        # one any more, but a row written directly to the store could, and the
        # derivation is the last place that can refuse it.
        return CriterionStatus(
            criterion=criterion, verdict=HUMAN_PENDING, evidence=latest,
            stale_reason="this was recorded as accepted, but it answers no "
                         "question anyone was asked, so it is not honoured")
    # A machine check can never satisfy a criterion only a person can judge.
    # Recording one is a bug in the caller; refusing to honour it here is the
    # difference between a guard and a suggestion.
    if criterion.verify_kind == "human" and verdict == PASSED:
        return CriterionStatus(
            criterion=criterion, verdict=HUMAN_PENDING, evidence=latest,
            stale_reason="a machine check cannot satisfy a criterion that "
                         "only a person can judge")
    return CriterionStatus(criterion=criterion, verdict=verdict,
                           evidence=latest, stale_reason="")


def derive_state(*,
                 has_requirement: bool,
                 criteria: Iterable[Criterion],
                 evidence: Iterable[Evidence],
                 revision: int,
                 artifact_digest: str,
                 has_implementation: bool,
                 contract_sealed: bool = True,
                 legacy_status: str = "") -> Verdict:
    """The one deterministic answer to "what state is this in now?".

    Precedence, and the argument for each step:

      FAILING   beats everything. A current, required, refuted criterion is the
                single most important thing to say, and burying it under a
                count of what passed is how "mostly done" gets reported.
      COMPLETE  only when every required criterion is satisfied by CURRENT
                evidence. Not "no failures" — every one of them, positively.
      PASSING   machine work is finished and something still needs a person.
                Distinguished from COMPLETE because "the tests pass" and "this
                is done" are different claims and the user is owed the
                difference.
      PARTIAL   some required criteria demonstrated, others not.
      SCAFFOLD  implementation exists, nothing demonstrated yet.
      PLANNED   criteria exist, implementation does not.
      IDEA      not even that.
    """
    crits = list(criteria)
    evs = list(evidence)
    statuses = tuple(
        current_verdict_for(c, evs, revision=revision, artifact_digest=artifact_digest)
        for c in crits
    )
    required = tuple(s for s in statuses if s.criterion.required)
    failing = tuple(s for s in required if s.verdict == FAILED)
    satisfied = tuple(s for s in required if s.verdict in SATISFYING)
    outstanding = tuple(s for s in required if s.verdict not in SATISFYING
                        and s.verdict != FAILED)
    human_blocked = tuple(s for s in outstanding if s.verdict == HUMAN_PENDING)

    legacy_note = ""
    if legacy_status:
        # Constraint from review: a pre-Stage-14 "complete" string is history,
        # not evidence. It was produced by a rule that never consulted the
        # user's request, so promoting it into COMPLETE would import exactly
        # the defect this module exists to remove.
        legacy_note = (
            f"a pre-Stage-14 status of '{legacy_status}' is recorded for this "
            "project. It was produced without acceptance criteria and is kept "
            "as history only; the current state is derived from criteria and "
            "evidence, and reaching COMPLETE again requires revalidation.")

    def out(state: str, *reasons: str) -> Verdict:
        return Verdict(state=state, reasons=tuple(r for r in reasons if r),
                       criteria=statuses, revision=revision,
                       artifact_digest=artifact_digest,
                       outstanding=outstanding, failing=failing,
                       legacy_status=legacy_status, legacy_note=legacy_note)

    if not has_requirement:
        return out(IDEA, "no durable requirement has been recorded")
    if not crits:
        return out(IDEA, "a requirement exists but no acceptance criteria have "
                         "been agreed for it")
    if failing:
        return out(FAILING,
                   f"{len(failing)} required criterion/criteria are currently "
                   f"failing",
                   *(f"failing: {s.criterion.text}" for s in failing[:3]))
    if not has_implementation:
        return out(PLANNED, f"{len(required)} required criteria recorded; no "
                            "implementation artifacts exist yet")
    if not required:
        # Every criterion is optional. Nothing is being required, so nothing is
        # outstanding — but calling that COMPLETE would let an empty required
        # set certify anything, which is the vacuous-truth hole Stage 13C kept
        # finding in my own tests. It is PASSING at best.
        return out(PASSING, "no criterion is marked required, so completion "
                            "cannot be established")
    if not outstanding:
        if not contract_sealed:
            # Everything recorded passes, but the contract was never agreed to
            # be the whole of what was asked. Completing here would mean
            # "everything we happened to write down is done", which is exactly
            # how a forgotten requirement becomes a finished project.
            return out(PASSING,
                       "every recorded criterion passes, but the acceptance "
                       "contract for this revision has not been sealed, so it "
                       "is not established that these are all of them")
        return out(COMPLETE,
                   f"all {len(required)} required criteria have current "
                   f"passing or explicitly accepted evidence")
    if len(human_blocked) == len(outstanding):
        return out(PASSING,
                   f"every machine-checkable criterion passes; "
                   f"{len(human_blocked)} awaiting a person",
                   *(f"awaiting you: {s.criterion.text}" for s in human_blocked[:3]))
    if satisfied:
        return out(PARTIALLY_IMPLEMENTED,
                   f"{len(satisfied)} of {len(required)} required criteria "
                   f"demonstrated",
                   *(f"still unproven: {s.criterion.text}" for s in outstanding[:3]))
    return out(SCAFFOLDED,
               f"implementation artifacts exist, but none of the "
               f"{len(required)} required criteria have been demonstrated",
               *(f"unproven: {s.criterion.text}" for s in outstanding[:3]))
